Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
 end
  #
  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    uname -r
    sudo dnf install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    sudo rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    sudo dnf makecache
    sudo dnf --enablerepo="elrepo-kernel" install -y kernel-ml
    sudo systemctl reboot
    uname -r  
  SHELL
end
